appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: hAezUsVbXSTFLGQDFNnGmxFkTwLTo6ccBz/RHMItG3PMVoPPVDTbfGtyvb8SM44VNkpDtOUbhukBWtIs1HMrnDJEc78by+4uIyiyXkF12RKpmRsznIPYBOzy1Xa9i/uh3rtQr2vcl8OP2Xf55gfkBHbF9KAAb3ljcZSRdAMrpHR9Ig6N6MJBTtzyvvUK4jBgSVeZI8MgJlAE0PV77PotC4SgMsxx+ilZ6ANFQ2Srjwc+ADpLYe4xndAA2nn9ee/C7/ogfmcT3KKyyvVsONPA9HzrzTqTJ1o7/qo8TeksPgXzH0FqZt9YVAVvHl36HqaoaUZLP3qBHNzKFv+w/Lk481VqEvUKXnO59uPtnQfzQuj5znFBz6MYMFb0Q2lVpJUSXUS223Flx+p8e8P6L/pkU3Im0nkWEgBlrJdkoC4piC6OZ+k/F7PTWdq5OgnJIXy18Ywg3bMwJPKJuBGM+vbBjFXZ/CCtN7bf3AqeNGtpNtD6Y2CzTv1jAMLYj3W/aX2IWPM8SFlExOY9+YzNQbyzTgnR/+MRAsHhqNie8OmpP3HFnQSRdv0LbLmJyBjeuX68Mfqc26khzE2bpOKLCD/seS7LDYFu22JEkEqBFhGgg53aODYW0vT5WzvvY0eCQXAJDq8aZmitZxYkLQeXRhJVHnZf6vsb55jsgBQmf4GcTwQ=
conda_forge_output_validation: true
